-- Seed the 11 baked Google testimonials into D1 as approved.
-- Safe to re-run: INSERT OR IGNORE skips rows that already exist.
-- Do not re-run d1/schema.sql.
--
-- Cloudflare D1 Console: paste the INSERT into Execute as one statement.
-- Wrangler: npx wrangler d1 execute wellness-needles --remote --file=d1/seed-google-reviews.sql

INSERT OR IGNORE INTO reviews (
  id, status, name, condition, reviewed_at, rating, source, emphasis, excerpt, body, created_at
) VALUES
  ('rev-luiza-barbi', 'approved', 'Luiza Barbi', 'Pain relief', '2026-08-10', 5, 'Verified Google review', 'for the first time in weeks, pain-free', 'for the first time in weeks, pain-free', 'I had a wonderful experience with Arkinth. I went for acupuncture after being in pain for about a month, and I was genuinely amazed by how much better I felt after my first session. I left feeling great and, for the first time in weeks, pain-free! Arkinth was very professional, attentive and welcoming. He took the time to listen and made me feel comfortable throughout the whole treatment. I''m really happy with my experience and already looking forward to my next session. I would definitely recommend him!', '2026-08-10T12:00:00.000Z'),
  ('rev-maria-bray', 'approved', 'Maria Bray', 'Gastritis & energy', '2026-08-04', 5, 'Verified Google review', 'from daily pain and discomfort with gastritis to no symptoms at all', 'from daily pain and discomfort with gastritis to no symptoms at all', 'Going to Arkinth for acupuncture has made a huge impact on my health, going from daily pain and discomfort with gastritis to no symptoms at all and an increase in energy levels and an overall feeling of being less stressed and a calmness in myself. Arkinth is excellent, very knowledgeable and has such kindness and understanding. I cannot recommend him enough, if your looking to try acupuncture or wanting to improve your health this is the place to go.', '2026-08-04T12:00:00.000Z'),
  ('rev-aidan-murphy', 'approved', 'Aidan Murphy', 'Sleep & energy', '2026-07-31', 5, 'Verified Google review', 'sleeping better and noticeably more energy', 'sleeping better and noticeably more energy', 'I have been to wellness needles twice and already I''ve seen the benefits of diet and lifestyle changes that were recommended - sleeping better and noticeably more energy...highly recommended..', '2026-07-31T12:00:00.000Z'),
  ('rev-christine-tuohy', 'approved', 'Christine Tuohy', 'Energy & wellbeing', '2026-07-28', 5, 'Verified Google review', 'I honestly couldn''t recommend him highly enough', 'I honestly couldn''t recommend him highly enough', 'I''ve had 6 treatments with Arkinth at Wellness Needles over the past few months, and I honestly couldn''t recommend him highly enough. From my very first appointment, he made me feel completely at ease. He took the time to listen, understand my needs, and tailor each treatment to support me. Every session has been a calm and relaxing experience. I''ve noticed a real improvement in my energy levels, and I always leave feeling refreshed, balanced, and well cared for. His professionalism, knowledge, and genuine kindness really stand out, and the clinic has such a welcoming and peaceful atmosphere. If you''re considering acupuncture, I would highly recommend Arkinth at Wellness Needles. It has been such a positive experience for me, and I''m very grateful for the care, support, and expertise he has provided over the past few months.', '2026-07-28T12:00:00.000Z'),
  ('rev-pavlo-nikulin', 'approved', 'Pavlo Nikulin', 'Lower back pain', '2026-07-22', 5, 'Verified Google review', 'it took only 2 sessions for Arkinth to deal with it', 'it took only 2 sessions for Arkinth to deal with it', 'I''ve had a very bad lower back pain and it took only 2 sessions for Arkinth to deal with it. I canot recommend him enough. Considering attitude, knowledge and willingness to help - absolutely amazing!', '2026-07-22T12:00:00.000Z'),
  ('rev-claire-maguire', 'approved', 'Claire Maguire', 'Digestive symptoms & aches', '2026-07-18', 5, 'Verified Google review', 'Within one session I noticed symptoms affecting my tummy going away', 'Within one session I noticed symptoms affecting my tummy going away', 'Within one session I noticed symptoms affecting my tummy going away. Other aches and pains (thinking it was peri menopause) have disappeared completely. It took 5-6 sessions and I can only say it was a miracle. Arkinth says its simple. Open the meridians and the body heals itself. So after 12 long years of doing acupuncture, energy healing, yoga, meditation and not shifting the discomfort in the body, I find Arkinth and he knows exactly what to do. It was like he had the key to open the door and the energy flows to the exact places where I needed to heal. The body has intelligence far beyond our understanding. My GP is officially deleted from my phone and I am taking my entire family to see Arkinth for up keep.', '2026-07-18T12:00:00.000Z'),
  ('rev-jen-bren', 'approved', 'Jen Bren', 'Healing & wellbeing', '2026-05-16', 5, 'Verified Google review', 'it was on another level', 'it was on another level', 'I have had acupuncture many times before and found it good. HOWEVER I had a treatment with Arkinth and it was on another level. Arkinth is genuinely interested in helping you heal, it was an excellent treatment and extremely relaxing. I would recommend this treatment to anyone that is interested in healing the body and improving their quality of life. Thank you so much. Jen :)', '2026-05-16T12:00:00.000Z'),
  ('rev-sue-hopkins', 'approved', 'Sue Hopkins', 'First session experience', '2026-04-19', 5, 'Verified Google review', 'I found Arkinth exceptional', 'I found Arkinth exceptional', 'Had my first session with Arkinth yesterday and i was so impressed; he is a such a highly skilled therapist; so genuine; with extensive knowledege and understanding you just know he really cares about his clients and there well being. I have went to a few different acupunturists over the years and I found Arkinth exceptional; his service is so unique and specialised I would highly reccommend his service', '2026-04-19T12:00:00.000Z'),
  ('rev-andrew-murphy', 'approved', 'Andrew Murphy', 'Shoulder pain, anxiety & depression', '2023-12-30', 5, 'Verified Google review', 'I am now pain free thanks to Arkinth', 'I am now pain free thanks to Arkinth', 'I have seen Arkinth for various issues. I had a reoccurring shoulder pain which was troubling me for years. After a few sessions with Arkinth the pain was almost gone. It allowed me to do the exercises suggested by the physio without having to take pain killers. I still regularly attend physio for the problem but I am now pain free thanks to Arkinth. I have also seen Arkinth for anxiety and depression. Getting through this involved life style changes as well as diet changes. Arkinth helped me with both. Very professional and passionate about helping people.', '2023-12-30T12:00:00.000Z'),
  ('rev-francisca-pereira', 'approved', 'Francisca Pereira', 'Fertility & anxiety', '2023-11-23', 5, 'Verified Google review', 'I found the treatment very effective and relaxing', 'I found the treatment very effective and relaxing', 'I would like to highly recommend Wellness Needles Clinic. I got acupuncture to help with fertility and anxiety. I found the treatment very effective and relaxing. Arkinth is very personable and professional.', '2023-11-23T12:00:00.000Z'),
  ('rev-viera', 'approved', 'Viera', 'Anxiety, sleep & energy', '2023-11-04', 5, 'Verified Google review', 'I am blooming, that I look more "alive"', 'I am blooming, that I look more "alive"', 'I was suffering from anxiety for a long time. I was feeling dizzy, tired, had constant ringing in my ears, couldn''t sleep in the night. The new symptoms were gradually adding up and worsening over the years. I was desperate and didn''t know what to do. Then my friend recommended me to try acupuncture. I contacted Arkinth. We had a conversation about my medical history and my current symptoms. He was very kind and I felt open to him. After only a few treatments I started to feel more energetic. Gradually I became a happier person and my symptoms were improving. Even my friends have noticed my changes. They were saying I am blooming, that I look more "alive".', '2023-11-04T12:00:00.000Z');
