name = "wellness-needles-reminders"
main = "src/index.ts"
compatibility_date = "2025-08-01"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "wellness-needles"
database_id = "b54abe22-54d7-40b7-bc83-553d11ed18c7"
