name = "wellness-needles-reminders"
main = "src/index.ts"
compatibility_date = "2025-08-01"

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "wellness-needles"
database_id = "6964be22-541f-42d7-bce3-213d12e68bc7"
